-- [[ Keybind Cheatsheet ]]
-- Opens a floating window with a formatted cheatsheet of all keybindings.
-- Depends on snacks.nvim (already installed, non-lazy).
local cheatsheet_win = nil

local lines = {
  "  MODE LEGEND",
  "  n = normal   i = insert   v = visual   x = visual (no select)",
  "  o = operator-pending   c = command line   t = terminal   - = any",
  "",
  "──────────────────────────────────────────────────",
  " NAVIGATION",
  "──────────────────────────────────────────────────",
  "Flash",
  "  n/x/o  s                Flash jump",
  "  n/x/o  S                Flash Treesitter",
  "  o      <A-r>            Remote flash",
  "  o/x    R                Treesitter search",
  "  c      <C-s>            Toggle Flash Search (in / prompt)",
  "",
  "Telescope",
  "  n      <leader><space>  Find files",
  "  n      <leader>ff       Find files",
  "  n      <leader>fg       Live grep",
  "  n      <leader>fb       Find buffers",
  "  n      <leader>fr       Recent files",
  "  n      <leader>fh       Help tags",
  "  n      <leader>fk       Find keymaps",
  "  n      <leader>fc       Config files",
  "  n      <leader>fp       Projects",
  "  n      <leader>fz       Z directories (zoxide)",
  "  n      <leader>,        Switch buffer",
  "",
  "  Telescope picker (inside any picker)",
  "  i      <C-j> / <C-k>   Move selection next/prev",
  "  i      <C-q>            Send selected to quickfix list",
  "  i      <C-x>            Delete buffer (buffers picker only)",
  "",
  "Treesitter Jumps",
  "  n      ]f / [f          Next/prev function start",
  "  n      ]F / [F          Next/prev function end",
  "  n      ]c / [c          Next/prev class start",
  "  n      ]C / [C          Next/prev class end",
  "",
  "tmux-navigator",
  "  n      <C-h/j/k/l>      Navigate panes (nvim + tmux)",
  "  n      <C-\\>            Previous pane",
  "",
  "──────────────────────────────────────────────────",
  " BUFFERS & WINDOWS",
  "──────────────────────────────────────────────────",
  "Barbar (Alt)",
  "  n      <A-,> / <A-.>    Prev/next buffer",
  "  n      <A-<> / <A->>   Move buffer left/right",
  "  n      <A-1..9>         Goto buffer 1-9",
  "  n      <A-0>            Goto last buffer",
  "  n      <A-c>            Close buffer",
  "  n      <A-p>            Pin buffer",
  "  n      <C-s-p>          Pick & delete buffer",
  "",
  "Buffers (Leader)",
  "  n      <leader>bn       New buffer",
  "  n      <leader>bd       Delete buffer",
  "  n      <leader>bD       Delete buffer (force)",
  "  n      <leader>bo       Delete other buffers",
  "  n      <leader>bx       Delete all buffers",
  "  n      <leader>bp       Pick buffer",
  "  n      <leader>bP       Pin buffer",
  "  n      <leader>bC       Restore buffer",
  "  n      <leader>be       Buffer explorer",
  "  n      <leader>b1..9    Goto buffer 1-9",
  "  n      <leader>b0       Goto last buffer",
  "  n      <leader>bdi      Sort by directory",
  "  n      <leader>bl       Sort by language",
  "  n      <leader>bN       Sort by name",
  "  n      <leader>bw       Sort by window number",
  "  n      <S-h> / <S-l>    Prev/next buffer",
  "",
  "Windows",
  "  n      <leader>wv       Split vertical",
  "  n      <leader>ws       Split horizontal",
  "  n      <leader>wc       Close window",
  "  n      <leader>wo       Close other windows",
  "  n      <leader>w=       Equal window size",
  "  n      <leader>wh/j/k/l Go to left/down/up/right window",
  "  n      <leader>-        Split below",
  "  n      <leader>\\        Split right",
  "",
  "──────────────────────────────────────────────────",
  " LSP & CODE",
  "──────────────────────────────────────────────────",
  "LSP",
  "  n      gd               Goto definition",
  "  n      gr               Goto references",
  "  n      gI               Goto implementation",
  "  n      gD               Goto declaration",
  "  n      K                Hover documentation",
  "  n      <leader>cd       Type definition",
  "  n      <leader>cs       Document symbols",
  "  n      <leader>cw       Workspace symbols",
  "  n      <leader>cr       Rename (IncRename)",
  "  n      <leader>ca       Code action",
  "  n      <leader>cf       Format buffer",
  "  n      <leader>ci       Toggle inlay hints",
  "  n      <leader>cm       Mason",
  "",
  "Diagnostics & Trouble",
  "  n      [d / ]d          Prev/next diagnostic",
  "  n      <leader>xx       Diagnostics (Trouble)",
  "  n      <leader>xX       Buffer diagnostics (Trouble)",
  "  n      <leader>xs       Symbols (Trouble)",
  "  n      <leader>xl       LSP definitions/refs (Trouble)",
  "  n      <leader>xL       Location list (Trouble)",
  "  n      <leader>xQ       Quickfix list (Trouble)",
  "",
  "──────────────────────────────────────────────────",
  " EDITING",
  "──────────────────────────────────────────────────",
  "Surround  (nvim-surround defaults)",
  "  n      ys{motion}{c}    Add surround",
  "  n      yS{motion}{c}    Add surround (opening/closing on own lines)",
  "  n      yss{c}           Add surround (whole line)",
  "  n      ySS{c}           Add surround (whole line, on own lines)",
  "  n      cs{c}{c}         Change surround",
  "  n      ds{c}            Delete surround",
  "  v      S{c}             Add surround (visual)",
  "  i      <C-g>s           Add surround (insert mode)",
  "  i      <C-g>S           Add surround on new lines (insert mode)",
  "",
  "Yanky",
  "  n/x    y                Yank (+ history)",
  "  n/x    p / P            Put after/before cursor",
  "  n/x    gp / gP          Put after/before selection",
  "  n      <A-o> / <A-i>    Cycle yank history prev/next",
  "  n      ]p / [p          Put indented after/before (linewise)",
  "  n      ]P / [P          Put indented after/before (uppercase)",
  "  n      >p / <p          Put and indent right/left",
  "  n      >P / <P          Put before and indent right/left",
  "  n      =p / =P          Put after/before applying filter",
  "  n      <leader>p        Yank history (Telescope)",
  "",
  "Autopairs",
  "  i      <M-e>            Fast wrap",
  "",
  "Treesitter Text Objects",
  "  o/v    af / if          Around/inside function",
  "  o/v    ac / ic          Around/inside class",
  "  o/v    al / il          Around/inside loop",
  "  o/v    aa / ia          Around/inside parameter",
  "",
  "Treesitter Selection",
  "  n      <C-space>        Init selection",
  "  v      <C-space>        Expand node (increment selection)",
  "  v      <BS>             Shrink node",
  "",
  "Move Lines (visual)",
  "  v      J / K            Move line down/up",
  "  v      < / >            Indent left/right (stay in visual)",
  "",
  "──────────────────────────────────────────────────",
  " COMPLETION  (insert mode)",
  "──────────────────────────────────────────────────",
  "blink.cmp",
  "  i      <C-space>        Show / toggle docs",
  "  i      <C-e>            Hide menu",
  "  i      <C-y>            Accept",
  "  i      <C-p> / <C-n>   Prev/next item",
  "  i      <C-b> / <C-f>   Scroll docs up/down",
  "  i      <Tab>            Accept / next snippet stop",
  "  i      <S-Tab>          Prev item / prev snippet stop",
  "",
  "──────────────────────────────────────────────────",
  " GIT",
  "──────────────────────────────────────────────────",
  "Gitsigns",
  "  n      ]h / [h          Next/prev hunk",
  "  n      <leader>gs       Stage hunk",
  "  v      <leader>gs       Stage hunk (range)",
  "  n      <leader>gr       Reset hunk",
  "  v      <leader>gr       Reset hunk (range)",
  "  n      <leader>gS       Stage buffer",
  "  n      <leader>gu       Undo stage hunk",
  "  n      <leader>gR       Reset buffer",
  "  n      <leader>gh       Preview hunk",
  "  n      <leader>gb       Blame line",
  "  n      <leader>gB       Toggle line blame",
  "  o/x    ih               Select hunk (text object)",
  "",
  "Git Conflict",
  "  n      co               Choose ours",
  "  n      ct               Choose theirs",
  "  n      cb               Choose both",
  "  n      c0               Choose none",
  "  n      ]x / [x          Next/prev conflict",
  "",
  "Other",
  "  n      <leader>gg       LazyGit (new tmux window)",
  "  n      <leader>gd       Diff view",
  "  n      <leader>gf       Diffview: file history",
  "  n      <leader>gl       Diffview: project history (log)",
  "  n      <leader>ge       Git explorer (neo-tree)",
  "",
  "──────────────────────────────────────────────────",
  " FOLDS",
  "──────────────────────────────────────────────────",
  "  n      zR / zM          Open/close all folds",
  "  n      zr / zm          Fold less/more",
  "  n      zo / zc          Open/close fold",
  "  n      zO / zC          Open/close recursively",
  "  n      za               Toggle fold",
  "  n      zp               Peek fold (or hover)",
  "",
  "  Leader mirrors (same actions via <leader>z*)",
  "  n      <leader>zR / zM  Open/close all folds",
  "  n      <leader>zr / zm  Fold less/more",
  "  n      <leader>zo / zc  Open/close fold",
  "  n      <leader>zO / zC  Open/close recursively",
  "  n      <leader>za       Toggle fold",
  "  n      <leader>zp       Peek fold",
  "",
  "──────────────────────────────────────────────────",
  " UI TOGGLES",
  "──────────────────────────────────────────────────",
  "  n      <leader>un       Toggle line numbers",
  "  n      <leader>ur       Toggle relative numbers",
  "  n      <leader>uw       Toggle word wrap",
  "  n      <leader>us       Toggle spell check",
  "  n      <leader>ua       Toggle auto-save",
  "  n      <leader>ud       Dismiss all notifications",
  "  n      <leader>ui       Toggle indent guides",
  "  n      <leader>ut       Toggle colorscheme (preview)",
  "  n      <leader>uz       Zen mode",
  "  n      [ou / ]ou        Soft/hard wrap mode",
  "  n      you              Toggle wrap mode",
  "",
  "──────────────────────────────────────────────────",
  " SESSIONS & QUIT",
  "──────────────────────────────────────────────────",
  "  n      <leader>qs       Restore session",
  "  n      <leader>qS       Select session",
  "  n      <leader>ql       Restore last session",
  "  n      <leader>qd       Don't save current session",
  "  n      <leader>qq       Quit all",
  "",
  "──────────────────────────────────────────────────",
  " SEARCH & NOTES",
  "──────────────────────────────────────────────────",
  "  n      <leader>sw       Search word under cursor",
  "  n      <leader>st       Search TODOs",
  "  n      ]t / [t          Next/prev TODO comment",
  "  n      <leader>.        Notification history",
  "  n      <leader>so       Open scratch",
  "  n      <leader>se       Export scratch",
  "  n      <leader>ss       Search fleeting notes",
  "",
  "Obsidian  (markdown buffers only)",
  "  n      gf               Follow link",
  "  n      <leader>ch       Toggle checkbox",
  "",
  "──────────────────────────────────────────────────",
  " OCTO / GITHUB",
  "──────────────────────────────────────────────────",
  "  n      <leader>oi       List GitHub Issues",
  "  n      <leader>op       List GitHub Pull Requests",
  "  n      <leader>od       List GitHub Discussions",
  "  n      <leader>on       List GitHub Notifications",
  "  n      <leader>os       Search GitHub",
  "",
  "──────────────────────────────────────────────────",
  " FILE EXPLORER (neo-tree window)",
  "──────────────────────────────────────────────────",
  "  n      <leader>e        Open explorer (root dir)",
  "  n      <leader>E        Open explorer (cwd)",
  "  n      <leader>ge       Git explorer",
  "  n      <leader>be       Buffer explorer",
  "",
  "  Inside neo-tree",
  "  -      l                Open / expand node",
  "  -      h                Close / collapse node",
  "  -      Y                Copy path to clipboard",
  "  -      O                Open with system application",
  "  -      P                Toggle preview",
  "",
  "──────────────────────────────────────────────────",
  " DEBUG (DAP)",
  "──────────────────────────────────────────────────",
  "  n      <leader>db       Toggle breakpoint",
  "  n      <leader>dB       Conditional breakpoint",
  "  n      <leader>dc       Continue",
  "  n      <leader>ds       Step over",
  "  n      <leader>di       Step into",
  "  n      <leader>do       Step out",
  "  n      <leader>dr       Open REPL",
  "  n      <leader>dl       Run last",
  "  n      <leader>dt       Terminate",
  "  n      <leader>du       Toggle DAP UI",
  "  n/v    <leader>de       Eval expression",
  "",
  "──────────────────────────────────────────────────",
  " MISC",
  "──────────────────────────────────────────────────",
  "  n      <Esc><Esc>       Clear search highlight",
  "  t      <Esc><Esc>       Exit terminal mode",
  "  n/i/v  <C-s>            Save file",
  "  n      <leader>l        Lazy",
  "  n      <leader>h        Check health",
  "  n      <leader>:        Command history",
  "  n/v/i/c <D-v>           Paste from clipboard",
  "  v      <D-c>            Copy to clipboard",
  "  n      u / <C-r>        Undo/redo (with highlight)",
  "  n      <leader>y        Copy file to clipboard",
  "  n      <leader>uu       Toggle undotree",
  "  n      <leader>?        This cheatsheet",
  "",
  "──────────────────────────────────────────────────",
  " VIM BUILT-INS",
  "──────────────────────────────────────────────────",
  "Word motion",
  "  n      w / W            Next word start (word / WORD)",
  "  n      b / B            Prev word start (word / WORD)",
  "  n      e / E            Next word end (word / WORD)",
  "  n      ge / gE          Prev word end (word / WORD)",
  "",
  "Line motion",
  "  n      0                Start of line (column 0)",
  "  n      ^                First non-blank character",
  "  n      $                End of line",
  "  n      g_               Last non-blank character",
  "  n      f{c} / F{c}      Jump to char forward/back (on)",
  "  n      t{c} / T{c}      Jump to char forward/back (before)",
  "  n      ; / ,            Repeat f/t forward/back",
  "",
  "File motion",
  "  n      gg / G           Top / bottom of file",
  "  n      {N}G             Goto line N",
  "  n      H / M / L        Top / middle / bottom of screen",
  "  n      % / {N}%         Matching bracket / N% of file",
  "  n      { / }            Prev / next empty line (paragraph)",
  "  n      <C-d> / <C-u>    Scroll half-page down/up",
  "  n      <C-f> / <C-b>    Scroll full-page forward/back",
  "  n      zz / zt / zb     Center / top / bottom current line",
  "",
  "Operators  (combine with motion or text object)",
  "  n      d{m}             Delete (into register)",
  "  n      c{m}             Change (delete + insert)",
  "  n      y{m}             Yank",
  "  n      >{m} / <{m}      Indent right/left",
  "  n      ={m}             Auto-indent",
  "  n      g~{m}            Toggle case",
  "  n      gu{m} / gU{m}    Lowercase / uppercase",
  "  n      dd / cc / yy     Delete/change/yank whole line",
  "  n      D / C            Delete/change to end of line",
  "  n      x / X            Delete char forward/back",
  "  n      r{c}             Replace char",
  "  n      s                Substitute char (→ insert)",
  "  n      ~                Toggle case of char under cursor",
  "  n      J                Join line below",
  "  n      .                Repeat last change",
  "",
  "Text objects  (use after d/c/y/v)",
  "  -      iw / aw          Inner / around word",
  "  -      iW / aW          Inner / around WORD",
  "  -      is / as          Inner / around sentence",
  "  -      ip / ap          Inner / around paragraph",
  "  -      i\" / a\"          Inner / around double quotes",
  "  -      i' / a'          Inner / around single quotes",
  "  -      i` / a`          Inner / around backticks",
  "  -      i( / a(          Inner / around parentheses",
  "  -      i[ / a[          Inner / around brackets",
  "  -      i{ / a{          Inner / around braces",
  "  -      i< / a<          Inner / around angle brackets",
  "  -      it / at          Inner / around HTML/XML tag",
  "",
  "Search",
  "  n      / {pat}          Search forward",
  "  n      ? {pat}          Search backward",
  "  n      n / N            Next / prev match",
  "  n      * / #            Search word under cursor fwd/back",
  "  n      g* / g#          Same but partial match",
  "",
  "Marks & jumps",
  "  n      m{a-z}           Set mark (local)",
  "  n      m{A-Z}           Set mark (global, cross-file)",
  "  n      '{m} / `{m}      Jump to mark (line / exact pos)",
  "  n      '' / ``          Jump to last position",
  "  n      <C-o> / <C-i>    Jump backward/forward in jumplist",
  "  n      g; / g,          Older/newer in changelist",
  "",
  "Registers & macros",
  "  n      q{a-z}           Record macro into register",
  "  n      q                Stop recording",
  "  n      @{a-z}           Play macro",
  "  n      @@               Repeat last macro",
  "  n      \"{r}{op}         Use register r for next op",
  "  n      :reg             Show all registers",
  "",
  "Visual mode",
  "  n      v / V / <C-v>    Char / line / block visual",
  "  v      o                Move to other end of selection",
  "  v      gv               Re-select last visual",
  "  v      u / U            Lowercase / uppercase selection",
  "",
  "Insert mode",
  "  i      <C-w>            Delete word back",
  "  i      <C-u>            Delete to line start",
  "  i      <C-r>{reg}       Insert register content",
  "  i      <C-o>{cmd}       Execute one normal command",
  "  i      <C-t> / <C-d>    Indent / de-indent line",
  "",
  "Command line",
  "  n      :s/old/new/g     Substitute in line",
  "  n      :%s/old/new/gc   Substitute in file (confirm)",
  "  n      :g/pat/cmd       Run cmd on lines matching pat",
  "  n      :norm {cmd}      Run normal cmd on each line",
  "  n      :.! {cmd}        Replace line with shell output",
  "  :      <C-r><C-w>       Insert word under cursor",
}

return {
  "folke/snacks.nvim",
  keys = {
    {
      "<leader>?",
      function()
        if cheatsheet_win and cheatsheet_win:valid() then
          cheatsheet_win:close()
          cheatsheet_win = nil
        else
          cheatsheet_win = Snacks.win({
            text = lines,
            enter = true,
            width = 0.75,
            height = 0.85,
            border = "single",
            title = " Keybinds ",
            title_pos = "center",
            ft = "text",
            wo = {
              wrap = false,
              cursorline = true,
              number = false,
              relativenumber = false,
            },
            keys = {
              q = "close",
            },
          })
        end
      end,
      desc = "Keybind cheatsheet",
    },
  },
}
