return {
  "Root-lee/screensaver.nvim",
  keys = {
    { "<leader>S", nil, desc = "Screensaver" },
    { "<leader>Ss", "<cmd>ScreensaverStop<cr>", desc = "Stop" },
    { "<leader>St", "<cmd>ScreensaverToggle<cr>", desc = "Toggle" },
    { "<leader>Sm", "<cmd>ScreensaverStart matrix<cr>", desc = "Matrix" },
    { "<leader>Sr", "<cmd>ScreensaverStart rain<cr>", desc = "Rain" },
    { "<leader>Sg", "<cmd>ScreensaverStart game_of_life<cr>", desc = "Game of Life" },
    { "<leader>S<", "<cmd>ScreensaverStart move_left<cr>", desc = "Move Left" },
    { "<leader>S>", "<cmd>ScreensaverStart move_right<cr>", desc = "Move Right" },
    { "<leader>Sc", "<cmd>ScreensaverStart scramble<cr>", desc = "Scramble" },
    { "<leader>Su", "<cmd>ScreensaverStart random_case<cr>", desc = "Random Case" },
    { "<leader>Sb", "<cmd>ScreensaverStart bounce<cr>", desc = "Bounce" },
    { "<leader>S*", "<cmd>ScreensaverStart starfield<cr>", desc = "Starfield" },
    { "<leader>Sp", "<cmd>ScreensaverStart pipes<cr>", desc = "Pipes" },
    { "<leader>Sf", "<cmd>ScreensaverStart fire<cr>", desc = "Fire" },
    { "<leader>Sn", "<cmd>ScreensaverStart snow<cr>", desc = "Snow" },
    { "<leader>Sz", "<cmd>ScreensaverStart zoo<cr>", desc = "Zoo" },
  },
  config = function()
    require("screensaver").setup({
      idle_ms = 5 * 60 * 1000, -- 5 minutes
      auto_start = true,
      disable_on_focus_lost = true,
      exit_key = "<Esc>",
      animations = {
        "matrix",
        "rain",
        "game_of_life",
        "move_left",
        "move_right",
        "scramble",
        "random_case",
        "bounce",
        "starfield",
        "pipes",
        "fire",
        "snow",
        "zoo",
      },
      winblend = 0,
    })
  end,
}
